#define CV_SHAPE_Pin GPIO_PIN_0
#define CV_SHAPE_GPIO_Port GPIOB
#define CV_SHAPE_Channel ADC_CHANNEL_8

#define CV_DIVMULT_Pin GPIO_PIN_1
#define CV_DIVMULT_GPIO_Port GPIOB
#define CV_DIVMULT_Channel ADC_CHANNEL_9

#define POT_OFFSET_Pin GPIO_PIN_1
#define POT_OFFSET_GPIO_Port GPIOA
#define POT_OFFSET_Channel ADC_CHANNEL_1

#define POT_SCALE_Pin GPIO_PIN_7
#define POT_SCALE_GPIO_Port GPIOA
#define POT_SCALE_Channel ADC_CHANNEL_7

#define POT_DIVMULT_Pin GPIO_PIN_2
#define POT_DIVMULT_GPIO_Port GPIOC
#define POT_DIVMULT_Channel ADC_CHANNEL_12

#define POT_SHAPE_Pin GPIO_PIN_0
#define POT_SHAPE_GPIO_Port GPIOC
#define POT_SHAPE_Channel ADC_CHANNEL_10

#define FAST_SAMPLE ADC_SAMPLETIME_480CYCLES
#define SLOW_SAMPLE ADC_SAMPLETIME_480CYCLES
#define OVERSAMPLE_RATIO 0
