#define CV_SHAPE_Pin GPIO_PIN_2
#define CV_SHAPE_GPIO_Port GPIOB
#define CV_SHAPE_Channel ADC_CHANNEL_15

#define CV_DIVMULT_Pin GPIO_PIN_12
#define CV_DIVMULT_GPIO_Port GPIOB
#define CV_DIVMULT_Channel ADC_CHANNEL_11

#define POT_OFFSET_Pin GPIO_PIN_6
#define POT_OFFSET_GPIO_Port GPIOA
#define POT_OFFSET_Channel ADC_CHANNEL_3

#define POT_SCALE_Pin GPIO_PIN_7
#define POT_SCALE_GPIO_Port GPIOA
#define POT_SCALE_Channel ADC_CHANNEL_4

#define POT_DIVMULT_Pin GPIO_PIN_11
#define POT_DIVMULT_GPIO_Port GPIOB
#define POT_DIVMULT_Channel ADC_CHANNEL_14

#define POT_SHAPE_Pin GPIO_PIN_2
#define POT_SHAPE_GPIO_Port GPIOB
#define POT_SHAPE_Channel ADC_CHANNEL_12

#define FAST_SAMPLE ADC_SAMPLETIME_24CYCLES_5
#define SLOW_SAMPLE ADC_SAMPLETIME_640CYCLES_5
#define OVERSAMPLE_RATIO ADC_OVERSAMPLING_RATIO_256
